<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created at' => 'Время создания',
    'Updated at' => 'Последнее обновление',
    'Be careful in Code field. Pay attention to field hint.' => 'Будьте внимательны при заполнении поля Код. Обратите внимание на подсказку.',
    'Can\'t delete system configuration value' => 'Нельзя удалить системное значение',
    'Code' => 'Код',
    'Config has been created' => 'Конфигурационное значение было успешно создано',
    'Config has been deleted' => 'Конфигурационное значение было удалено',
    'Config has been updated' => 'Конфигурационное значение было обновлено',
    'Configs' => 'Конфигурационные значения',
    'Create config' => 'Создать значение',
    'Created at {0, date, MMMM dd, YYYY HH:mm}' => 'Время создания: {0, date, dd MMMM YYYY, HH:mm}',
    'Information' => 'Информация',
    'Manage configs' => 'Управление конфигурацией',
    'Name' => 'Название',
    'No' => 'Нет',
    'No configuration code defined.' => 'Не задан код конфигурационного значения',
    'Only latin characters, numbers and symbols (.-_) allowed. Spaces not allowed.' => 'Разрешены только латинские буквы, числа и символы (.-_). Пробелы запрещены.',
    'Save' => 'Сохранить',
    'System' => 'Системное',
    'Update config' => 'Обновление конфигурации',
    'Value' => 'Значение',
    'Yes' => 'Да',
    '{0, date, MMMM dd, YYYY HH:mm}' => '{0, date, dd MMMM YYYY, HH:mm}',
];
